# Generated by Django 4.2.2 on 2023-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
