# Generated by Django 4.2.2 on 2023-06-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiot_api', '0002_alter_measurement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='datetime',
            new_name='measured_at',
        ),
    ]
