# Generated by Django 4.2.2 on 2023-06-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiot_api', '0003_rename_datetime_measurement_measured_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measured_at',
            new_name='datetime',
        ),
    ]
